<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGaPqk0x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGaPqk0x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGaPqk0x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGaPqk0x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGaPqk0x\App_KernelDevDebugContainer([
    'container.build_hash' => 'GaPqk0x',
    'container.build_id' => '8d5e66a4',
    'container.build_time' => 1617695424,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGaPqk0x');
