<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSSJmYLX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSSJmYLX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSSJmYLX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSSJmYLX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSSJmYLX\App_KernelDevDebugContainer([
    'container.build_hash' => 'SSJmYLX',
    'container.build_id' => 'ef8d3a4b',
    'container.build_time' => 1617712157,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSSJmYLX');
